backend/package-lock.json, backend/package.json, backend/src/app.js, backend/src/config/db.js
- added mongoose dependency
- added dotenv dependency
- connection to mongodb cluster working
=> [FEAT] Add Mongo DB & dotenv in BACKEND

backend/package-lock.json, backend/package.json, backend/src/server.js
- added bcrypt dependency
- added jsonwebtoken dependency
=> [FEAT] Add Bcrypt and JsonWebToken in BACKEND

backend/src/app.js, backend/src/controllers/auth.js, backend/src/routes/auth.js, backend/src/services/auth.js
- added auth register route and implemented functionality
- added comments for auth register controller and service functions
- added auth login route and implemented functionality
=> [FEAT] Add Authentication Endpoints in BACKEND

frontend/package-lock.json, frontend/package.json
- added react-router-dom dependency
=> [FEAT] Add React Router in FRONTEND

frontend/src/App.js, frontend/src/routes/RootRouter.js, frontend/src/routes/auth/Auth.js, frontend/src/routes/dashboard/Dashboard.js
- create basic dashboard page component
- create basic auth page component
- created root router component
- modified App.js to use RootRouter component
=> [FEAT] Add Pages in FRONTEND

backend/src/services/auth.js
- checking if email ready exists and hashing user password
=> [FEAT] Modify createNewUser in auth.js to check if email is unique and hash password in BACKEND

backend/.eslintrc.json, backend/src/services/auth.js
- added hash comparison in backend on user authenticate
- added eslint rule
=> [FEAT] Modify authenticateUser in auth.js to compare password with hash in BACKEND

frontend/src/index.css, frontend/src/routes/KimchiStonksApp/KimchiStonksApp.css, frontend/src/routes/KimchiStonksApp/KimchiStonksApp.js, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.css, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.js
- added kimchi stonks app background
- fleshed out nav bar component
- added nav bar implementation
=> [FEAT] Add navbar functionality in FRONTEND

frontend/src/components/Button/Button.css, frontend/src/components/InputField/InputField.css, frontend/src/index.css, frontend/src/routes/KimchiStonksApp/KimchiStonksApp.css, frontend/src/routes/KimchiStonksApp/KimchiStonksApp.js, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.css, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.js
=> [FEAT] Add navbar styling in FRONTEND

frontend/src/routes/KimchiStonksApp/NavBar/NavBar.css, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.css, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.js
- implemented user info bar component
- added styling to user info bar component
=> Add styling to the user info bar in FRONTEND

backend/package-lock.json, backend/package.json
- added nodemon dependency
- changed start script to use nodemon
=> [FEAT] Add nodemon for development in BACKEND

backend/.eslintrc.json, frontend/.eslintrc.json
- added linebreak style rule to eslint frontend
- added linebreak style rule to eslint backend
=> [MISC] Modify eslint rules for linebreak style in FRONTEND and BACKEND

frontend/src/routes/KimchiStonksApp/KimchiStonksApp.css, frontend/src/routes/KimchiStonksApp/Market/Market.css, frontend/src/routes/KimchiStonksApp/Market/Market.js
- modified app-container and main css to take up full screen
- added grid styling for market route
=> [FEAT] Add market route layout in FRONTEND

frontend/src/routes/KimchiStonksApp/KimchiStonksApp.css, frontend/src/routes/KimchiStonksApp/Market/Market.css, frontend/src/routes/KimchiStonksApp/Stock/Stock.css, frontend/src/routes/KimchiStonksApp/Stock/Stock.js
- added grid styling for stock route
=> [FEAT] Add stock route layout in FRONTEND

frontend/.eslintrc.json, frontend/public/index.html, frontend/src/components/Modal/Modal.css, frontend/src/components/Modal/Modal.js
- created modal component using portal
- updated eslint rules
=> [FEAT] Add modal dialog component for prompting user input in FRONTEND

frontend/src/components/Dialogs/AddBuyingPowerDialog/AddBuyingPowerDialog.css, frontend/src/components/Dialogs/AddBuyingPowerDialog/AddBuyingPowerDialog.js, frontend/src/components/Modal/Modal.css, frontend/src/routes/KimchiStonksApp/KimchiStonksApp.js, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.js
- created add buying power dialog component
- added add buying power dialog to routes
- added styling to add buying power dialog
=> [FEAT] Add buying power dialog component in FRONTEND

frontend/src/App.js, frontend/src/providers/AuthProvider.js, frontend/src/providers/AuthProvider/AuthProvider.js
- created auth context and auth provider component
- app is using using auth provider
=> [FEAT] Add global context in FRONTEND

backend/src/services/auth.js
added token to return json on user register and login
=> [FEAT] Add json web token to generate token for auth users in BACKEND

frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.js, frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.scss, frontend/src/routes/KimchiStonksApp/Dashboard/DashboardDummyHoldingsList.js, frontend/src/routes/KimchiStonksApp/Dashboard/DashboardDummyTitles.js, frontend/src/routes/KimchiStonksApp/TableHeader/TableHeader.js, frontend/src/routes/KimchiStonksApp/TableHeader/TableHeader.scss, frontend/src/routes/KimchiStonksApp/TableRow/TableRow.js, frontend/src/routes/KimchiStonksApp/TableRow/TableRow.scss
Added dashboard title, created tableheader and tablerow components for the holdings table
=> [FEAT] Add holdings table and title for dashboard

frontend/src/components/Table/Table.js, frontend/src/components/Table/Table.scss
Added styling and clickable hover to table
=> [FEAT] Add hyperlink/clickable to the holdings table rows

backend/src/mongodb/schemas/stockSchema.js, backend/src/mongodb/schemas/userSchema.js
Adding the stock schema to the backend of the application
=> [FEAT] Add stock schema 

frontend/src/components/Dialogs/AddBuyingPowerDialog/AddBuyingPowerDialog.scss, frontend/src/routes/KimchiStonksApp/KimchiStonksApp.js, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.scss, frontend/src/routes/KimchiStonksApp/Stock/Stock.js, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.js, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.scss
- created stock utility component
- added styling for stock utility component
=> [FEAT] Add implementation and styling of market prediction and purchase container in FRONTEND

frontend/.eslintrc.json, frontend/package-lock.json, frontend/package.json, frontend/src/routes/KimchiStonksApp/Stock/Stock.js, frontend/src/routes/KimchiStonksApp/Stock/Stock.scss, frontend/src/routes/KimchiStonksApp/Stock/StockGraph/StockGraph.js, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.js
- added chart.js dependency
- stock graph fits in container perfectly
- implemented and styled stock graph
=> [FEAT] Add chart.js in and implement stock graph FRONTEND

backend/src/services/auth.js, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.js
- removed console logs
- user info bar using auth user info
=> [FEAT] Add dynamic user data to user info bar in FRONTEND

backend/src/controllers/dashboard.js, backend/src/routes/dashboard.js
- redefine dashboard endpoints
- implement get stock overview endpoint
=> [FEAT] Add Dashboard Endpoints in BACKEND

backend/src/routes/auth.js, frontend/src/contexts/Auth.js
- changed autoLogin route end point to auto-login
- updated auto login call in frontend to match updated backend route end point
=> [MISC] Modify the auto login route endpoint to use kebab case in BACKEND and all calls in FRONTEND

backend/src/controllers/dashboard.js, backend/src/routes/dashboard.js
- added validate user middleware to dashboard routes
- changed path parameter id to symbol
- updated dashboard controller
=> [MISC] Modify dashboard routes and controllers in BACKEND

backend/src/app.js, backend/src/controllers/user.js, backend/src/routes/user.js, backend/src/services/user.js
- updated app.js
- updated user route endpoints
- added validate user middleware to user route end points
- updated user controller with JS documentation for each function
- removed unecessary comments from user service
=> [MISC] Modify user endpoints in BACKEND

backend/src/controllers/dashboard.js, backend/src/routes/dashboard.js
- intraday: return only 10:00 to 16:00, 60min interval
- daily: return only (up to) last 7 days
- monthly: return only (up to) last 12 months
- yearly: return only (up to) last 10 years
- search: restrict to US region only
- return more useful error message when stock symbol is invalid
=> [MISC] Modify dashboard endpoints in BACKEND

backend/src/controllers/dashboard.js, frontend/src/components/Dialogs/AddBuyingPowerDialog/AddBuyingPowerDialog.js, frontend/src/components/InputField/InputField.js, frontend/src/components/Table/Table.js, frontend/src/contexts/Auth.js, frontend/src/contexts/Stock.js, frontend/src/routes/KimchiStonksApp/KimchiStonksApp.js, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.js, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.scss, frontend/src/routes/KimchiStonksApp/NavBar/StockSearch/StockSearch.js, frontend/src/routes/KimchiStonksApp/NavBar/StockSearch/StockSearch.scss, frontend/src/routes/KimchiStonksApp/Stock/Stock.js, frontend/src/routes/KimchiStonksApp/Stock/StockGraph/StockGraph.js
- connected add buying power with backend API
- adding buying power working
- added stock context
- create stock search component
- styled stock search suggestions dropdown
- updated suggestions styling to be absolute
- remove suggestions when search is empty
- recieving stock data on search
- modifed stock intraday time series response
=> [FEAT] Add communication between app and api in FRONTEND

backend/src/controllers/dashboard.js
- search endpoint now using yahoo finance API to get around rate-limited calls
=> [MISC] Modify search endpoint in BACKEND

backend/src/controllers/dashboard.js
- search endpoint errors are now caught and returned
=> [BUG] Catch errors in search endpoint in BACKEND 

frontend/src/routes/KimchiStonksApp/Stock/Stock.js, frontend/src/routes/KimchiStonksApp/Stock/Stock.scss, frontend/src/routes/KimchiStonksApp/Stock/StockOverview/StockOverview.js
- implemented stock overview and styled
=> [FEAT] Add stock overview implementation in FRONTEND

backend/src/controllers/dashboard.js, frontend/src/components/Button/Button.scss, frontend/src/contexts/Stock.js, frontend/src/routes/KimchiStonksApp/NavBar/StockSearch/StockSearch.js, frontend/src/routes/KimchiStonksApp/Stock/Stock.js, frontend/src/routes/KimchiStonksApp/Stock/Stock.scss, frontend/src/routes/KimchiStonksApp/Stock/StockGraph/StockGraph.js
- added time period buttons to stock graph component
- change time period button if active
- on time period button click change query param
- change stock data to corresponding time period
- updated x axis naming for week and month
=> [FEAT] Add stock graph options in FRONTEND

frontend/src/components/Table/Table.js, frontend/src/components/Table/Table.scss, frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.js, frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.scss, frontend/src/routes/KimchiStonksApp/Market/Market.js, frontend/src/routes/KimchiStonksApp/Market/Market.scss
- refactored table and dashboard
- updated holdings dashboard
- connected trending stocks to wall street
- linked trending stock row click to stock page
=> [FEAT] Add table to wall street in FRONTEND

backend/src/controllers/user.js, backend/src/mongodb/schemas/stockSchema.js, backend/src/services/user.js, frontend/src/components/Table/Table.js, frontend/src/contexts/Auth.js, frontend/src/contexts/Stock.js, frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.js, frontend/src/routes/KimchiStonksApp/Market/Market.js, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.js
- added retrieve user info method to auth context
- updated retrieve user info response
- refactored user buy stock route
- connected use buy stock to endpoint
- updated stock schema
=> [FEAT] Add buy stock functionality by connecting to endpoint in FRONTEND

frontend/src/contexts/Stock.js, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.js
* Added in predicted price in StockUtility
* Added in current prediction into Stock.js context
* Added in extra get requests to obtain day, month and year prices
=> [FEAT] Added predicted price into StockUtility.js

backend/src/controllers/dashboard.js
- simplify return data
- add current price
=> [MISC] Simplify overview endpoint in BACKEND

backend/src/controllers/dashboard.js
- updated intraday endpoint to use Yahoo API
=> [MISC] Replace AV API with Yahoo in BACKEND - Intraday

backend/src/controllers/dashboard.js
- updated overview endpoint to use TheStreet API
=> [MISC] Replace AV API with TheStreet in BACKEND - Overview

backend/src/services/auth.js, backend/src/services/user.js, frontend/src/components/Dialogs/AddBuyingPowerDialog/AddBuyingPowerDialog.js, frontend/src/components/Dialogs/SellStocksDialog/SellStocksDialog.js, frontend/src/components/Dialogs/TextDialog/TextDialog.js, frontend/src/components/Dialogs/TextDialog/TextDialog.scss, frontend/src/components/InputField/InputField.js, frontend/src/contexts/Auth.js, frontend/src/contexts/Stock.js, frontend/src/routes/Auth/LoginForm/LoginForm.js, frontend/src/routes/Auth/RegisterForm/RegisterForm.js, frontend/src/routes/KimchiStonksApp/Stock/Stock.js, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.js
- modified auth service
- created text dialog component
- added login unsuccessful dialog
- added register unsuccessful dialog
- added add buying power success/unsuccessful dialog
- added sell stocks success/unsuccessful dialog
- added buy stocks success/unsuccessful dialog
=> [FEAT] Add missing dialogs in FRONTEND

backend/src/controllers/dashboard.js, backend/src/routes/dashboard.js
- updated overview endpoint to use WSJ API
- updated daily endpoint to use Yahoo API
- updated monthly endpoint to use Yahoo API
- updated yearly endpoint to use Yahoo API
- updated prediction to not use AV API
=> [MISC] Replace AV API with Yahoo in BACKEND

backend/src/controllers/dashboard.js
- 52 week high/low and prediction are now converted and formatted correctly for the frontend
=> [BUG] Fix 52 week high/low and prediction in BACKEND

frontend/src/index.scss, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.js, frontend/src/routes/KimchiStonksApp/NavBar/NavBar.scss, frontend/src/routes/KimchiStonksApp/NavBar/StockSearch/StockSearch.scss, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.js, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.scss
Updated navbar and user info to be more responsive
- Read commit messages for more specific change detail
=> [FEAT] Add UI responsiveness to FRONTEND

frontend/src/components/Button/Button.scss, frontend/src/components/Dialogs/AddBuyingPowerDialog/AddBuyingPowerDialog.js, frontend/src/components/Dialogs/SellStocksDialog/SellStocksDialog.js, frontend/src/routes/KimchiStonksApp/Stock/Stock.js, frontend/src/routes/KimchiStonksApp/Stock/StockOverview/StockOverview.js
- fixed disabled button bug
- fixed uncontrolled input
=> [BUG] Remove on hover effect for disabled buttons in FRONTEND

backend/src/services/auth.js, backend/src/services/user.js, frontend/src/components/Dialogs/AddBuyingPowerDialog/AddBuyingPowerDialog.js, frontend/src/components/Dialogs/SellStocksDialog/SellStocksDialog.js, frontend/src/components/Dialogs/TextDialog/TextDialog.js, frontend/src/components/Modal/Modal.js, frontend/src/components/Table/Table.js, frontend/src/contexts/Auth.js, frontend/src/contexts/Stock.js, frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.js, frontend/src/routes/KimchiStonksApp/KimchiStonksApp.js, frontend/src/routes/KimchiStonksApp/Market/Market.js, frontend/src/routes/KimchiStonksApp/NavBar/StockSearch/StockSearch.scss, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.js, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.scss, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.js, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.scss
- removed shares from user info bar
- price in wall st page to exactly 2 decimal points
- added current price to stock utility component
- updated buying
- buying and selling shares working
- fixed user endpoints
- updated user endpoint
- total change in holdings is dynamic and using endpoint data
=> [FEAT] Modify to fix bugs in FRONTEND

frontend/src/components/Table/Table.js, frontend/src/components/Table/Table.scss, frontend/src/index.scss, frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.js, frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.scss, frontend/src/routes/KimchiStonksApp/Market/Market.js, frontend/src/routes/KimchiStonksApp/UserInfoBar/UserInfoBar.scss
- Updated styling for the table component so that overflow is scrollable and does not unnecessarily stretch the screen
- Also applied a minor change to user info to accommodate for the removal of the total shares info container
=> [FEAT] Add scrolling functionality to holdings and tables

frontend/src/routes/KimchiStonksApp/Dashboard/Dashboard.scss, frontend/src/routes/KimchiStonksApp/Market/Market.scss, frontend/src/routes/KimchiStonksApp/Stock/Stock.scss, frontend/src/routes/KimchiStonksApp/Stock/StockUtility/StockUtility.scss
- Added responsive sizing to the stock page so that it collapses at screen widths < 1200px
=> [FEAT] Add fixed sizing to stock graphs

backend/package-lock.json, backend/package.json, backend/src/controllers/dashboard.js, backend/src/middleware/validateUser.js, backend/src/mongodb/db.js, backend/src/routes/__tests__/dashboard_test.js, backend/src/routes/dashboard.js, backend/src/server.js, backend/src/services/auth.js, backend/src/services/user.js
- added tests for each endpoint, checking the return data format
=> [TEST] Dashboard endpoint tests in BACKEND

backend/.env, backend/.gitignore, backend/src/controllers/dashboard.js, backend/src/middleware/validateUser.js, backend/src/mongodb/db.js, backend/src/services/auth.js, backend/src/services/user.js
- add environment variables back to .env file
- include .env file in repo
=> [MISC] Environment variables
